### ISSUE TITLE
Can't write after uploading application data with ETS

### ISSUE THREAD

**Issue by Gonzo4** [Supergiovane/node-red-contrib-knx-ultimate#110]
Hi,
when I'm uploading the Application data with ETS, I can't write to the bus with KNX ultimate afterwards. I'm using knxd, when I restart the knxd service its working again. Redeploying or restarting the Node-RED service doesn't help. Receiving messages does always work. Sending messages with the knxEasy nodes work also (see picture)

![grafik](https://user-images.githubusercontent.com/6013729/103891692-99553680-50ea-11eb-8d73-1eb5df2fc865.png)

The node configuration:

![grafik](https://user-images.githubusercontent.com/6013729/103891912-f0f3a200-50ea-11eb-9e87-4f6f898f2da8.png)

gateway configuration:

![grafik](https://user-images.githubusercontent.com/6013729/103891999-1b455f80-50eb-11eb-9e36-84692c8bd315.png)

... the checkbox "Echo von gesendeten Telegram an alle Nodes mit gleichen Gruppenadressen" was disabled temporary, with this checkbox checked it doesn't work ether

**Comment by Supergiovane** [comment]
Hi Gonzo
what verion of knx-ultimate do you have installed?

**Comment by Gonzo4** [comment]
...sorry I forgot :pensive:
- node-red-contrib-knx-ultimate: 1.2.5
- node-red: 1.0.6

**Comment by Supergiovane** [comment]
The only thing that comes into my mind, is that you have two knx-ultimate nodes with the same group address, but with different Datapoint.
Can you check it, please?
Other than that, does it work if you don't load the ETS file?
Other than that 2, you should never use two knx nodes on the same flow. KNXD may be affected by that.

**Comment by Gonzo4** [comment]
I have reduced it to one knx-node and removed the ETS file => Same problem...
Sometimes it works after the application upload, but in the most cases not.
Another curiosity: If I create a copy of the flow and enable flow 2 and disable flow 1 and vise versa, sometimes a write will work sometimes not?!

![grafik](https://user-images.githubusercontent.com/6013729/103934509-60868300-5125-11eb-879e-d8dc452c8f40.png)

**Comment by Supergiovane** [comment]
I suspect an issue with knxd. 
Have you seen this? https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/5.-FAQ-Troubleshoot
There is a suggestion about filter tables. 
You can also check to increase the delay between telegrams. 
If you’re running nodered on Raspberry, please be sure to either select an ethernet card in the gateway config window, or disable whe wifi card. 

Since when you have these issues?
Is there particular things you’ve done, prior to having problems?

**Comment by Gonzo4** [comment]
Yes, I've read the FAQ, but sometimes it works and sometimes not...
I have played around with the parameters, I think a **de**crease of the delay does the trick (default was 40ms):

![grafik](https://user-images.githubusercontent.com/6013729/103939930-d93d0d80-512c-11eb-8354-4f8b07e3da17.png)

I have entered a wrong interface name => a error message was shown periodically. But I could not stop the message by fixing an redeploying until I reboot the Pi, like there is something running in the background? The application upload generates a few thousand messages, maybe a queue in the background is running full or something like that?

I have made only a simple flow for tests so far with knxEasy. For productive things I wanted to use knx ultimate, so I have no experience with knx ultimate so far...

But it's running now with the decreased delay, thanks so far. I will keep an eye on it if it's stable..

**Comment by Supergiovane** [comment]
Ho Gonzo
Knx-Ultimate is rock solid and has many active installations. 
I suggest you to use a real knx router, to avoid unnecessary layers of possible trouble. 
As i wrote, don’t install two knx nodes from different developers at the same time. Uninstall knxeasy or knx-ultimate. 
The warnings you see during import, should be fixed by setting the right datapoints in ETS. This forces you to do the right things for a succesfull installation. 
:-)
Let me know how it works in the next days.
