### ISSUE TITLE
Logger doesn't record from NR sent Telegrams

### ISSUE THREAD

**Issue by Namakemono93** [Supergiovane/node-red-contrib-knx-ultimate#117]
Hi Supergiovane

Sorry for bothering you again, but it looks like I found a bug:

I have set up a KNX logger but it seems like it doesn't record any telegrams which are sent from the KNX Ultimate to the KNX bus:

Log directly recorded in the ETS:
![ETS Log](https://user-images.githubusercontent.com/52327137/111957736-afb93e80-8aec-11eb-84f6-9567c39a1716.png)

Log recorded by KNX Ultimate:
![KNX Ultimate Log](https://user-images.githubusercontent.com/52327137/111957762-b778e300-8aec-11eb-9800-2fc43054bb6f.png)

1.1.251 is the IP interface that is used for both, connection for the ETS and KNX Ultimate.

I use the KNX Ultimate 1.2.11 and the "Echo" is set on.

Or did I set up something wrong?
Many thanks,
Simon

**Comment by Supergiovane** [comment]
Hi,
let me check it. I'll revert to you ASAP.

**Comment by Supergiovane** [comment]
Hi
I tested yet and for me, it works great with KNX Router. As you can see here, "0/1/2" is a telegram sent every 1 second from a KNX-Ultimate node.
<img width="713" alt="Istantanea_22_03_21__09_50" src="https://user-images.githubusercontent.com/37666636/111963705-1b52da00-8af4-11eb-9a2b-62f8ec36d36a.png">

As for KNX/IP **Interface**, like yours, there is a known issue because the IP Interface doesn't broadcasts the datagram like a router, so the telegrams coming from a KNX-Device itself, won't be logged.
I'll work on it and hope to release a new version with this addition, in the next days.

**Comment by Supergiovane** [comment]
Hi,
if i send you some files, are you able to copy it in the .node-red path of your PC where node-red is running?

**Comment by Supergiovane** [comment]
You should unzip the content of the attached file, to your **.node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api/src** folder, replacing the existing files.
Then restart nodered.
It should work.

[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/6182884/Archivio.zip)

**Comment by Namakemono93** [comment]
Hi,
I will test it tomorrow, thanks for the fast support!

**Comment by Namakemono93** [comment]
Okay, I just tested it. The problem now is I can't open the XML.
I get this Error in the ETS:
![image](https://user-images.githubusercontent.com/52327137/112026378-6ee61780-8b36-11eb-886b-ceb3ce876930.png)

Could it be that the Telegram RawData is too long?
![image](https://user-images.githubusercontent.com/52327137/112026491-8f15d680-8b36-11eb-8dfb-c160799db3b0.png)

Here the file, maybe you can open it:
[test.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/6183880/test.zip)

**Comment by Supergiovane** [comment]
Yes it can be. 
Tomorrow i’ll take a look again. Thanks

**Comment by Supergiovane** [comment]
Hi again
unfortunately, i cannot fix it yet. I'm working on KNX Secure and the code is a mess now.
I tried to solve the issue in a dirty and quick way, without luck.
Sorry, you have either to buy a KN/IP Router or wait some time....

**Comment by heleon19** [comment]
Hi Supergiovane
It's really great how well KNX Ultimate works now. Thanks again for this!

Recording telegrams also for IP interfaces would be quite helpful in troubleshooting. Could we support you with that?

Regards Heleon

**Comment by Supergiovane** [comment]
Hi Reto,
many thanks for your donation!!
The code i have here on my Macbook is a little a mess now and i cannot switch my mind elsewhere, because i'm in study on how to implement knx secure.

The issue with IP Interface, is that the interface itself doesn't echoes the sent datagrams by itself (knx-logger node uses that echo coming from the websocket, to extract the cEMI in the function FSM.prototype.onUdpSocketMessage and to put it into the **datagram.cemi.cemiETS** property).

In case of an IP Interface, a cEMI hex string must be recreated from scratch while sending the datagram to the wires. In the **FMS.js**, the function  **sendDatagram** sends the datagram to the KNX wires and here, there is the **sm.emitEvent(datagram)** method, used to manually send an echo all KNX-Ultimates nodes belonging to the sender's group address.
Here, the variable  **datagram** should have ** datagram.cemi.cemiETS** property containing the cEMI hex string recreated from the **datagram** json object.
This [guy](https://github.com/advancedKnx/advanced_knx/blob/master/src/RawMod/KnxNetRebuildMessageBytes.js) has already done something similar, but it seems not fully working.

**Comment by heleon19** [comment]
Hi Massimo
Thank you for your feedback. I'll check, maybe I can find something. Hold you up to date.
Thanks Reto

**Comment by heleon19** [comment]
Hi again
I changed "2900" to "2e00" so it is "to Bus", but thats not the main issue.
And in the catch was dg instead of datagram.

With boolean types its working on my side. I have to check Simons file with the long RawData.

I get now  on startup:
[error] 3/23/2021, 4:08:29 PM KnxUltimate-API: Buffer should be 1 byte long
[error] 3/23/2021, 4:08:29 PM KnxUltimate-API: Buffer should be 1 byte long
[error] 3/23/2021, 4:08:29 PM KnxUltimate-API: Buffer should be 1 byte long
[error] 3/23/2021, 4:08:29 PM KnxUltimate-API: Buffer should be 1 byte long
[error] 3/23/2021, 4:08:29 PM KnxUltimate-API: Buffer should be 1 byte long
[error] 3/23/2021, 4:08:29 PM KnxUltimate-API: Buffer should be 1 byte long
[error] 3/23/2021, 4:08:29 PM KnxUltimate-API: Buffer should be 1 byte long
[error] 3/23/2021, 4:08:29 PM KnxUltimate-API: Buffer should be 1 byte long
[error] 3/23/2021, 4:08:29 PM KnxUltimate-API: Buffer should be 1 byte long
[error] 3/23/2021, 4:08:29 PM KnxUltimate-API: DPT3: Buffer should be 1 byte long
[error] 3/23/2021, 4:08:29 PM KnxUltimate-API: DPT3: Buffer should be 1 byte long
[error] 3/23/2021, 4:08:29 PM KnxUltimate-API: Buffer should be 3 bytes long. Received undefined
[error] 3/23/2021, 4:08:29 PM KnxUltimate-API: DP18: Buffer should be 1 byte long


The changed code:
let cemiETS = cemiBUFForETS.toString("hex");
datagram.cemi.cemiETS = "2e00" + cemiETS.substring(cemiETS.indexOf("bce"));
//console.log("BANANA CEMI TRASMETTO", datagram.cemi.cemiETS);
} catch (error) { datagram.cemi.cemiETS = ""; }

**Comment by Supergiovane** [comment]
Hi Reto,
yes, with boolean it works. With other more long cEMI not.
I think it can be fixed, but yet absolutely not. Maybe as soon as the first beta of the knx secure connection will be out.
Maybe a smart quickfix-workaround-holycrapwhatbadcode can help, but for now, i'm committed to knx secure.

**Comment by heleon19** [comment]
Hi Massimo
Will KNX Secure be part of KNX Ultimate? Looking forward to it. Where do you find all the time?

**Comment by Supergiovane** [comment]
The right question is: where do you find the documentation?
It’s a mess. The official one is nearly useless and way too generalist. I’m loosing a lot of time, but i love my job/passion and the red zone, here in Italy, helps a lot, because we cannot exit home.

**Comment by HLeithner** [comment]
@Supergiovane you talk about https://my.knx.org/en/shop/knx-specifications and the 103 pages KNX Data Security DP Dokument?

**Comment by heleon19** [comment]
Only for information (after the success of KNX secure ;-)), I checked Simons faulty telegram
![image](https://user-images.githubusercontent.com/10326318/112226733-d67f8e00-8c2e-11eb-8869-b172bf49a92d.png)
It should be 
![image](https://user-images.githubusercontent.com/10326318/112226898-19d9fc80-8c2f-11eb-9d86-b28fce25795a.png)
So in ETS it looks like
![image](https://user-images.githubusercontent.com/10326318/112226980-370ecb00-8c2f-11eb-939c-15b965635136.png)

Interesting is the Flag 'a', it's comming from "bee". Any idea why KNX Ultimate sends with the 'a' flag?

**Comment by Supergiovane** [comment]
> @Supergiovane you talk about https://my.knx.org/en/shop/knx-specifications and the 103 pages KNX Data Security DP Dokument?

Hi
Exaclty. The knx secure part of that seems to be outdated as well and on the internet i searched for a more recent version and found something.

**Comment by Supergiovane** [comment]
> Only for information (after the success of KNX secure ;-)), I checked Simons faulty telegram
> ![image](https://user-images.githubusercontent.com/10326318/112226733-d67f8e00-8c2e-11eb-8869-b172bf49a92d.png)
> It should be
> ![image](https://user-images.githubusercontent.com/10326318/112226898-19d9fc80-8c2f-11eb-9d86-b28fce25795a.png)
> So in ETS it looks like
> ![image](https://user-images.githubusercontent.com/10326318/112226980-370ecb00-8c2f-11eb-939c-15b965635136.png)
> 
> Interesting is the Flag 'a', it's comming from "bee". Any idea why KNX Ultimate sends with the 'a' flag?
> 
> Finally I modified your code, I'm not sure about the tunnstate header_length. I took 6 bytes.
> try {
> //console.log("datagram =", datagram);
> const cemiOffset = datagram.header_length + (datagram.hasOwnProperty("tunnstate") ? 6 : 0);
> let cemiETS = cemiBUFForETS.toString("hex");
> datagram.cemi.cemiETS = "2e00" + cemiETS.substring(cemiOffset * 2);
> // console.log("cemiETS =", datagram.cemi.cemiETS);
> //console.log("BANANA CEMI TRASMETTO", datagram.cemi.cemiETS);
> } catch (error) { datagram.cemi.cemiETS = ""; }

Thanks. 
i’ll paste it into my code and try.

**Comment by Namakemono93** [comment]
> 
> 
> The right question is: where do you find the documentation?
> It’s a mess. The official one is nearly useless and way too generalist. I’m loosing a lot of time, but i love my job/passion and the red zone, here in Italy, helps a lot, because we cannot exit home.

Maybe @KHBuchner can help you since they already have a KNX Secure gateway?

**Comment by Supergiovane** [comment]
I'm looking at [Calimero](https://github.com/calimero-project/calimero-core), despite in Java, it seems it has already an implementation of KNX-Secure.

**Comment by Supergiovane** [comment]
@Namakemono93 Simon,
Can you put the content of this zip
[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/6204740/Archivio.zip)
here: **.node-red/node_modules/node-red-contrib-knx-ultimate/nodes**

And the content of this zip
[knxultimate-api.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/6204744/knxultimate-api.zip)
here **.node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api/src** please?

Then restart nodered and try.
PS: you'll notice some BANANA logs but don't worry. They will be deleted thereafter.

**Comment by Namakemono93** [comment]
Hi Massimo
This seems to work for me now. I tested On/Off and % Values.
Thanks!

**Comment by Supergiovane** [comment]
Hi Simon
can you live with BANANA logs for now, or must i remove it? The new version will be out in this weekend without the BANANA.

**Comment by Namakemono93** [comment]
No worries, I can live with that ;-)
