### ISSUE TITLE
Problems with rbe in circular flow

### ISSUE THREAD

**Issue by dos-ise** [Supergiovane/node-red-contrib-knx-ultimate#138]
Hi Supergiovane,

first of all thanks for your great work. :)

**Describe the bug**
I want to connect a KNX ga with an homematic thermostat in an circular flow. (See screenshot)
So I would be able to control the device manually and via my knx visualization.
But if i change the value for example from 19.0 to 19.5 it get trigger in circular and my knx bus get spammed with alternating telegramms wit 19.0 and 19.5.  

I thought this would be handled with rbe enabled at the knx node. Am I doing something wrong?

**To Reproduce**
See Flow in screenshot

**Expected behavior**
Any value change to be triggerd once.

**Screenshots**
![image](https://user-images.githubusercontent.com/20043350/132456274-8fb73634-5fee-4c8e-bdf8-93e6e1443da4.png)

**Knx-Ultimate Version**
1.2.36

**Are you running node-red behind homematic, docker or anything similar?**
Node-Red on rasberrymatic on an pi3

**Comment by Supergiovane** [comment]
Hi Dos
Does the homematic node support half celsius (0.5) ?
What happens if you delete the link exiting from knx ultimate and entering to homematic node?
You should try to enable both input and output rbe filters on knx-ultimate, but in reality, you haven’t the same temperature repeated, instead you have two setpoints alternating. Someone is unable to properly set the setpoint. You should start inspecting this behaviour.

**Comment by dos-ise** [comment]
If I remove any of the two connections it works oneway. 
The homematic node does support 0.5

**Comment by Supergiovane** [comment]
KNX-Ultimate outputs 19.5 as expected?
