### ISSUE TITLE
KNX USB Interface

### ISSUE THREAD

**Issue by choppychop** [Supergiovane/node-red-contrib-knx-ultimate#153]
Hi Max,

Hope you are well and thanks for the great work, KNX Ultimate is my favorite node-red node these days.

I've just got my hands on a KNX USB Interface and wondered if I could use that instead of an IP interface with KNX Ultimate. Its a Weinzierl 332, and I'm running node-red on a pi3.

https://www.weinzierl.de/index.php/en/all-knx/knx-devices-en/knx-usb-interface-332-en

I have got an IP Interface as well and I've been using that for ages with no problems, but I just thought a pi with a usb straight to the KNX bus was a tidy solution if you can't rely on the network 24/7.

Not sure if it's the same question but working with a KNX pi hat would be great as well, I bought one a while ago from ZDI a while ago but after hours of messing around with knxd and pi config I gave up on it so now it's a paperweight.

https://www.tindie.com/products/zdi/knx-shield-with-rtc-and-24v-power-input/

Anyway I know you're a busy man and this would be low on the priority list but I thought I'd ask just in case.

Thanks again and keep up the good work,

Iain

**Comment by Supergiovane** [comment]
Hi Lain,
many users do use knxd with USB interfaces and KNX-Ultimate, so maybe you can stick with that.
As per the native support, sorry, but i've no plans to implement that, because i'm alone as developer and i'm currently focused on KNX IP Secure.
Personally, to avoid that a network issue can take down my node-red, i use two ethernet interface on node-red. One connected with my LAN and one directly and straight connected to a KNX/IP interface. 
If my LAN Unifi stuffs goes down for any reason, node-red is still able to communicate to the KNX/IP interface and to do the job without issue.
Maybe you can also follow this idea.
