### ISSUE TITLE
Node not connecting to IP/KNX router

### ISSUE THREAD

**Issue by rvbaelen** [Supergiovane/node-red-contrib-knx-ultimate#230]
Hello

:) so first tings first. Disclaimer: novice at work... i'm pretty sure it is not related to KNX-Ultimate node, but docker/container related... 

I'm using node red in a container (because setup and keeping things up to date is easy for a novice like me, untill something go's wrong an then it's horrible).
the container's network is configured as host so node red should act like running on the host (so multicast from inside the conainer and receiving messages from my KNX IP router should not be a problem).
My knx ultimate gateway points to 224.0.23.12:3671 (what works on a rpi not using docker), and is also configured to use eth0 (not the docker port), does not auto connect, but connects after i inject true in the KNX watchdog to msg.connectGateway.
I cannot get the node to connect to my knx/IP router. the node does state connected "on duty" but does not send anything on the KNX bus.

The watchdog connected to the multicast address failes to ping.
I've tried a node setup with unicast UDP to the IP address of my router, the watchdog states Basic check level unicast Ethernet - interface ok. But later fails and then reconnects. (when using these settings on the nodes still nothing sends out to the knx bus).

I found it hard to get other info related to this problem except giving up the docker.... but that is no fix for me.

On your FAQ u mention "If you're running Node-Red in a container, delay the start of node-red after the container boots up. Some users report that the Ethernet card is still DOWN when node-red starts. You can try it by manually stop node-red, disabling auto start of noder-red at boot, reboot the container, wait 2-3 minutes and manually start node-red. If KNX-Ultimate works, the issue is that."

 Could this be the solution to my problem? As i am not that familiar with docker/containers... how do i do this step by step for the node-red container.... can u or someone with the same issues help me out?

Thanks in advance.

**Knx-Ultimate Version** 1.4.13

**Comment by Supergiovane** [comment]
Hello.
First of all, thank you for stating your "novice advisory". I appreciate that, because i can talk with you easily.
As i can see, you are a pretty skilled user, indeed.
You should be sure that no firewall are in place in your docker container.
From the docker host machine, you should be able to open a terminal window (if you're using proxmox, the button is labelled "console", if QNAP, the button should be something like ">_").
From the terminal, try to ping the IP of your KNX Router (the individual IP, not the multicast one).
If successfull, the issue is related either in the docker host firewall, or in the network switcher. If you're using Unifi network switches, be sure that your switch doesn't block multicast on the port where the docker's host cable is plugged into.

If all these solutions fails and if you're able, you could install a VM with debian and node-red, instead of using docker. It's simpler as you tough and it works.
On dockerized images, you haven't any clue nor control on what is installed, where and how.
For example, the nodejs version could be too old. You could check the nodejs version, by issuing "node -v" from a prompt command window.

Let me know..

**Comment by rvbaelen** [comment]
pinging from the terminal inside the container works to the ip adres of the knx router. KNX Ultimate and works on a pi without docker, so the docker host firewall is the problem? the docker is configured as host so there should be no "firewall", also i opend the port 3671 and other KNX related ports.

**Comment by Supergiovane** [comment]
Hi
I've had only issues with docker, not only with KNX, but also with other apps.
What docker container machine are you using? Can you please also issue a "node -v" command from that container's terminal?

**Comment by Supergiovane** [comment]
..and... can you check also, wether your ethernet switch has some protection active, like UDP storm protection?

**Comment by rvbaelen** [comment]
i'm using docker/portainer on an armbian sbc... node -v returns v16.16.0 will try to figure out the UDP sotrm protection later today. But since the RPI on the same network does work... i should exclude the network no?

**Comment by Supergiovane** [comment]
Hi
It depends. The switch could do some stuffs on the ethernet port, if on that port, there it sees more than one MAC address.
But i'm guessing...
At first, let check the simplest things, then will check wether the portainer is the culprit.

**Comment by rvbaelen** [comment]
I cannot find any udp storm protection active or any other related stuff on the switch, no fiters on multicast. But the port has more than one mac on the port (because there are two switches between the ip knx router and my sbc)

**Comment by Supergiovane** [comment]
Try to connect the pc and the knx router directly, with a straight cable, or use a very dummy switch.
