### ISSUE TITLE
Version 1.1.16 - sequence of telegrams is not kept

### ISSUE THREAD

**Issue by egs2003** [Supergiovane/node-red-contrib-knx-ultimate#26]
Due to the built-in delay of 60ms the sequence of telegrams is not kept. For example, I control several roller shutters simultaneously. First the shutter stop command is sent and then the desired position. 
The new update now has the effect that in some cases the position is first sent to the KNX bus and immediately afterwards the stop command. This means that the roller shutter does not move into the desired position.

**Comment by Supergiovane** [comment]
Hello Marcel
Please don’t rely on telegram sequences. 
Because the communication is UDP, you will have no control over multiple telegrams sent at the same time, due to the nature of the UDP stack. 
The built in delay act as Buffer by keeping the sequence intact, but as soon as the node sends the UDP telegrams to the KNX router, you loose the sequency control. 
Insert a delay node between stop and move and then let me know.

**Comment by Supergiovane** [comment]
Hello,
I'll try tomorrow to implement the delay in another way, to fix your issue.

**Comment by Supergiovane** [comment]
Fixed in v. 1.1.18
