### ISSUE TITLE
Set msg topic for group adress

### ISSUE THREAD

**Issue by pkess** [Supergiovane/node-red-contrib-knx-ultimate#32]
When reading in data from sensors it may be usefull when i can configure the topic value output message of the block

**Comment by Supergiovane** [comment]
Hello
Can you tell me an example please?

**Comment by pkess** [comment]
![image](https://user-images.githubusercontent.com/11859624/73971038-7ccede00-491e-11ea-83a6-0bf35e9322d7.png)

As you see in the picture above i am using your nodes to get the data from the bus (In fact some temperatures, the power currently used for my home and the energy counter value for my home.
I added some node after these values to combine them to lines in a csv file.
This is the code for the AggregateCsv function:
```javascript
context.data = context.data || {
    Time: 0,
    TempWohnz: 0,
    TempSchlafz: 0,
    CounterkWh: 0,
    PowerkW: 0
};
switch(msg.topic) {
    case "Time":
        context.data.Time = msg.payload;
        msg = null;
        return {payload:context.data};
    case "TempWohnz":
        context.data.TempWohnz = msg.payload;
        msg = null;
        break;
    case "TempSchlafz":
        context.data.TempSchlafz = msg.payload;
        msg = null;
        break;
    case "CounterkWh":
        context.data.CounterkWh = msg.payload;
        msg = null;
        break;
    case "PowerkW":
        context.data.PowerkW = msg.payload;
        msg = null;
        break;
}
```

The code of e.g. the PowerkW function looks like
```javascript
msg.payload = msg.payload / 1000.0;
msg.topic = "PowerkW";
return msg;
```

I could avoid these extra functions if i could just set the topic directly in the knx node and apply a factor like suggested in #31

**Comment by pkess** [comment]
I just tried to implement something what would work for me. You can review this in https://github.com/pkess/node-red-contrib-knx-ultimate/tree/overwrite_topic

While working on this i just recognized that the topic is already set with the associated group address.

Please feel free to tell me your thoughts.

**Comment by Supergiovane** [comment]
Hello
The output msg node is located here https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/3.-Messages-from-the-node

Your work makes sense, but you’re trying to pack all your particular needs into the knx-ultimate node itself. I think that your flow is just amazing and it’s way more flexible than having packed all in knx-ultimate node. 
Imagine when you’ll need, for example, one more field for a database or so. With your current flow, you can simply add this field to one of your function, instead of ditching into knxultimate node to add this more field as well. 
;-)

**Comment by heleon19** [comment]
Hi Supergiovane

I would support the message topic option. It's a common Node-RED thing, I could use it as well.

ex. inject node:
![image](https://user-images.githubusercontent.com/10326318/74006395-db767500-497b-11ea-8cba-589b54ab9665.png)

**Comment by Supergiovane** [comment]
Hello heleon,
the node already outputs a topic, corresponding to the Group Address, that you can change with a simple msg.topic function or with a "change" node.
You two do propose to allow the user to change the topic to whatever you want.
Because there are users relying to the fact that the current "topic" is equal to "group address", i must elaborate the matter more in depth, and think to a backward compatible solution.
I'll think about today and i'll let you two know a possible solution for that.
Cheers.

**Comment by heleon19** [comment]
I agree you should not break the "interface" for existing users/flows. What about to have a "message topic", in case it has an value and only when it has an vlaue to overwrite the msg.topic?

**Comment by Supergiovane** [comment]
Yes, i'm thinking about it. But actually if you changes the group address, the topic changes accordingly. I'm gonna find a way to mantain this automation thus allow some degrees of freedom. Thanks.

**Comment by Supergiovane** [comment]
V. 1.1.28 will be out soon, with Topic property.
Wiki has been updated to reflect the changes.
Example have been update to reflect the changes.
Loop prevention have been updated to reflect the changes, as well as Flood protection.
