### ISSUE TITLE
"knxUltimate: Bind KNX Bus to interface error: E_CONNSTATE_LOST"

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-knx-ultimate#6]
Hi @Supergiovane ，

The version I used before did not report this error, but when I upgraded to version 1.1.8, my debug window always reported this error. What is the reason?

This is my configuration
![image](https://user-images.githubusercontent.com/26770241/63931460-e3a2be00-ca87-11e9-90dd-561da0844720.png)

Best Regrads
songzh

**Comment by Supergiovane** [comment]
Hello songzh, 
will take a look but it seems, that your PC loses the ethernet connection with your interface.
Seems you're using a KNX IP Interface. The KNX IP interface lost connection essentially when 
1) you've too many connection to the tunnel
2) you got a problem on the ethernet interface, for example lost IP packets.
If your node is continuing to work properly, then you can simply don't care about it, because the node will auto-reconnect and this process is transparent for you.
Let me know, instead, if you experience losing of communication. 
For example, when you see this log, try to switch on and off a light using node-red "inject" node and let me know it the light turns off and on or not.
Thanks

**Comment by Supergiovane** [comment]
PS: THANK YOU FOR THE PAYPAL DONATION !!!!!!

**Comment by songzh96** [comment]
> PS: THANK YOU FOR THE PAYPAL DONATION !!!!!!

This is nothing, in addition, thank you very much for writing the plugin.

Yes, I probably connected 223 nodes, I tried to send a message to the red node, it worked.

Is there any way to avoid connection loss?

Is this bug a problem with my gateway issue or KNX.js plugin?

BEST REGARDS
songzh

**Comment by Supergiovane** [comment]
Hello songzh,
that's an isue with the IP Interfaces in general, not only with yours.
The KNX IP Interfaces acts different than an KNX IP Router (routers costs more than interfaces).
To be able to communicate to an IP Interface, the KNX stack must open an unicast connection, mimic the TCP communication (connect to ip interface, get an ID, then use this ID for subsequent communications). 
Routers works differently, using a single multicast IP, that differs from the IP you set in the interface (in your example, 192.168.30.3).
An IP interface can accept a maximum fixed number of simultaneous connection.
In case, for example, node-red is running and you open ETS as well, the tunnel will saturate and begins discard the LAN packets.
With Router, you don't have any limitation on how many connection you have.
What IP Interface are you using?

**Comment by songzh96** [comment]
I have 2 knx-ip,one is made in china，another is knx-ip-baos-777.
now I connect knx-Ultimate to a gateway separately using a tunneling.
It will also report the error.

my hadware is raspberry.

**Comment by songzh96** [comment]
knx-Ultimate connect to knx-ip-baos-777. the knx-gateway only one connect.

**Comment by Supergiovane** [comment]
I'm trying yet to reproduce your issue, i've an Enertex IP Interface up and running for you.
Until now, no disconnections.
I noticed you have "Bind to local interface" set to a specific ethernet. I suppose your raspberry does have 1 ethernet + 1 Wifi.
Does Ethernet and Wifi card have the same subnet? In your case, 192.168.30.xxxxx ?
If yes, you can try to change one or another. I've the fear, that the Raspberry does have problems handling both interfaces, if both are on the same subnet.

**Comment by songzh96** [comment]
my raspberry eth0:192.168.30.6 wifi:192.168.31.248

**Comment by Supergiovane** [comment]
So no problem with subnets.
Currently my test machine is running without issue.
Do you have some Video over IP streaming devices on the same LAN switch of the raspberry, or do you have some devices making high traffic, for example, IP Security camera?

It seems that some packets will lost. 
E_CONNSTATE_LOST is not a critical error, is more a warning and practically you don't lost the connection to the IP Interface. 
You have a problem in your lan anyway and it was better to solve this problem, because it can influence other stuffs.
Before 1.1.8, the node have been set to log only critical errors. With 1.1.8, it logs any type of error.
If this is annoying for you, i can disable the non critical log.

**Comment by songzh96** [comment]
> So no problem with subnets.
> Currently my test machine is running without issue.
> Do you have some Video over IP streaming devices on the same LAN switch of the raspberry, or do you have some devices making high traffic, for example, IP Security camera?
> 
> It seems that some packets are lost.
> E_CONNSTATE_LOST is not a critical error, is more a warning and practically you don't lost the connection to the IP Interface.
> You have a problem in your lan anyway and it's better to solve this problem, because it can influence other stuffs.
> Before 1.1.8, the node was set to log only critical errors. With 1.1.8, it logs any type of error.
> If this is annoying for you, i can disable the non critical log.

I just tested it with a separate network. It is normal and I have not reported an error. It should be a network problem on my side. My monitoring equipment is in lan 192.168.10.x, I am not too clear about the network configuration, because it is a professional configuration.

Thank you for your answer.

Also, are you interested in developing some knx plugins, just like your current plugin. I am a system integrator. I am also looking at the underlying protocol of knx and trying to develop a knx gateway. If you are interested, feel free to contact me. My contact information: 986758232@qq.com, or songzh1996@gmail.com.

BEST REGARDS
songzh
