### ISSUE TITLE
WATCHDOG node improvement

### ISSUE THREAD

**Issue by croghostrider** [Supergiovane/node-red-contrib-knx-ultimate#95]
Hi Supergiovane,

your node is amazing I use it since May in a KNX project with 2007 devices as KNX Logger without failure.

A nice to have feature for the WATCHDOG node would be the possibility to check if the device with the phy. address x.x.x exists.
My inspiration was the [ABB EUB/S1.1](https://new.abb.com/products/2CDG110066R0011/eub-s1-1-eib-monitoring-unit-mdrc). Then we can also use the WATCHDOG node as WATCHDOG for the KNX devices.

Regards

**Comment by Supergiovane** [comment]
Hi Crog
The ABB is an interesting device.
Thanks for your suggestion, but unfortunately what you ask is out of the scope of the watchdog node, that is checking only if the KNX/IP gateway is working properly.
Querying all devices in an installation via physical address goes beyond my actual knowledge, because i'm only focused only on KNX datagrams (and it's already a lot work!).
